wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698852166.295719
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 76
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 76
      - 77
      3:
      - 1
      - 23
      4: 3.10.11
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
